### DISCUSSION TITLE
Did anyone tried this project with selfhosted litellm proxy server ?

### DISCUSSION THREAD

**Discussion by Greatz08** [simonw/llm#1141] [Q&A]
OpenAI-compatible models supported, but i did'nt understand this if i see from litellm perspective : 

> - model_id: orca-openai-compat
>   model_name: orca-mini-3b.ggmlv3
>   api_base: "http://localhost:8080"

This is litellm config.yaml format :

model_list:
  - model_name: groq-llama3-70b-8192
    litellm_params:
    api_base: [URL]
    api_key: [API KEY]

so i have to use model id and name of litellm one in this project yaml ? or different name ?

**Comment by gyanu2507** [comment]
Two different YAML files, two different `model_name` meanings.

LiteLLM's `model_name` is the public id clients send in `{"model": "..."}`. `llm` extra YAML is local: `model_id` is what you type as `llm -m ...`, and `model_name` is the string `llm` puts in that JSON body.

Point `llm` at the proxy, and make those two strings match:

```yaml
# ~/.config/io.datasette.llm/extra-openai-models.yaml
- model_id: groq-llama
  model_name: groq-llama3-70b-8192
  api_base: "http://localhost:4000/v1"
  api_key: "sk-anything"
```

```yaml
# litellm config.yaml
model_list:
  - model_name: groq-llama3-70b-8192
    litellm_params:
      model: groq/llama3-70b-8192
      api_key: os.environ/GROQ_API_KEY
```

`llm -m groq-llama "hi"` then POSTS to LiteLLM with `"model": "groq-llama3-70b-8192"`, which LiteLLM routes. You can pick any `model_id` you want. `model_name` has to be LiteLLM's `model_name`, not the underlying provider slug, unless you configured them to be equal.

`api_base` should include `/v1` if that is how you mounted the OpenAI-compatible listener. A missing `/v1` is the usual 404.
