### DISCUSSION TITLE
A configuration for deepinfra.com

### DISCUSSION THREAD

**Discussion by rikhuijzer** [simonw/llm#478] [Show and tell]
The following configuration can be used to get Llama 3 70B running on deepinfra.com.

Add the following to `extra-openai-models.yaml`:
```yaml
- model_id: 'deepinfra-llama3'
  model_name: 'meta-llama/Meta-Llama-3-70B-Instruct'
  api_base: 'https://api.deepinfra.com/v1/openai'
  api_key_name: 'deepinfra'
  completion: false
```
and set the key via
```sh
$ llm keys set deepinfra
```
