### ISSUE TITLE
Structured Extraction w/ Function Calls

### ISSUE THREAD

**Issue by jxnl** [simonw/llm#113]
Hey I wrote a small [lib](https://openai-function-call.onrender.com/) around using function calls and pydatnic for extraction and i think some ideas could be appleid via the CLI or API
I really like the CLI interface so i'd love to brain some some ways of doing the extraction via CLI.

Heres an [example from my docs](https://openai-function-call.onrender.com/examples/search/)

The simplest is defining a model and making the model use it 

```python
class UserDetails(BaseModel):
    "Correctly extracted user information"
    name: str = Field(..., description="User's full name")
    age: int
```

Suggestion:
```
model("gpt-4", response_model=UserDetails)
```

In the template you could even support some pattern like:

```
model: gpt-4
system: Extract out a user detail
prompt: "look at {input} and ..."
response_model:
    - UserDetail
       description: ...
       parameters: 
           - name
             type: str 
            ...
```

But a more interesting use case could be configuring it to extract Multiple UserDetails

```
class UserDetails(BaseModel):
    "Correctly extracted user information"
    name: str = Field(..., description="User's full name")
    age: int
    
class MultipleDetails(BaseModel):
    batch: List[UserDetails]
```

If this was implemented well you could imagine having some cli tool out as jsonlines vs a single json object. It could even be streamed!

```
curl -s '...' | \
  strip-tags -m | llm --extract-multiple schema.json
```
returns 
```
{name: .., age: ...}
{name: .., age: ...}
```
