### ISSUE TITLE
Question: how to set a custom header with a stored key? (from inside: extra-openai-models.yaml)

### ISSUE THREAD

**Issue by iamFIREcracker** [simonw/llm#1183]
I would like to use llm and target a _private_ LLM; since the deployment has an OpenAI compatible API, I gave extra-openai-models.yaml a shot, and this is what I came up with so far:

```
- model_id: llama33-70b-neuron
  model_name: llama33-70b-neuron
  api_base: [...]/v1
  headers:
    x-api-key: [...]
```

First things first: it's working, so that's great.

Having said that, I was wondering if there was some kind of templating support that would allow me to read the key from keys.json, rather than storing it here, in clear.  Again, minor annoyance, but I was curious about it.

Thanks.
