### ISSUE TITLE
ReadTheDocs builds are failing

### ISSUE THREAD

**Issue by simonw** [simonw/llm#128]
https://readthedocs.org/projects/llm/builds/21391357/

<img width="831" alt="image" src="https://github.com/simonw/llm/assets/9599/e4e1efd2-8523-46b2-9abc-0f62a5f5cb82">

https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by simonw** [comment]
I think this will work:
```yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

formats:
   - pdf
   - epub

python:
   install:
   - requirements: docs/requirements.txt
```
