### ISSUE TITLE
Bring back LLM_OPENAI_SHOW_RESPONSES option

### ISSUE THREAD

**Issue by simonw** [simonw/llm#404]
I replaced that with `OPENAI_LOG` in https://github.com/simonw/llm/commit/214fcaaf86383d199a5f282ebb77c0eecd85cbe8

But this issue reminded me that it's really useful to be able to see the full requests and responses:
- #364

**Comment by simonw** [comment]
Here's the previous implementation which used `requests`:

https://github.com/simonw/llm/blob/e9a6998ca38946cfef75bdb7535d8bdc652ef381/llm/default_plugins/openai_models.py#L19-L26

But OpenAI switched to `httpx` in their 1.0 library release.

**Comment by simonw** [comment]
I can achieve this with `httpx` event hooks: https://www.python-httpx.org/advanced/#event-hooks

The `OpenAI()` constructor takes an optional `http_client: httpx.Client | None = None` parameter: https://github.com/openai/openai-python/blob/0c1e58d511bd60c4dd47ea8a8c0820dc2d013d1d/src/openai/_client.py#L78C1-L78C49

Here's a quick demo of event hooks:

```pycon
>>> captured=[]
>>> def log_request(request):
...     captured.append(request)
...     print(f"Request event hook: {request.method} {request.url} - Waiting for response")
... 
>>> def log_response(response):
...     captured.append(response)
...     request = response.request
...     print(f"Response event hook: {request.method} {request.url} - Status {response.status_code}")
... 
>>> client = httpx.Client(event_hooks={'request': [log_request], 'response': [log_response]})
>>> client.get("https://www.example.com/")
Request event hook: GET https://www.example.com/ - Waiting for response
Response event hook: GET https://www.example.com/ - Status 200
<Response [200 OK]>
>>> captured
[<Request('GET', 'https://www.example.com/')>, <Response [200 OK]>]
>>> captured[0]
<Request('GET', 'https://www.example.com/')>
>>> captured[0].content
b''
>>> captured[1].content
b'<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset="utf-8" />\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <style type="text/css">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.</p>\n    <p><a href="https://www.iana.org/domains/example">More information...</a></p>\n</div>\n</body>\n</html>\n'
>>> captured[1].text
'<!doctype html>\n<html>\n<head>\n    <title>Example Domain</title>\n\n    <meta charset="utf-8" />\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1" />\n    <style type="text/css">\n    body {\n        background-color: #f0f0f2;\n        margin: 0;\n        padding: 0;\n        font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n        \n    }\n    div {\n        width: 600px;\n        margin: 5em auto;\n        padding: 2em;\n        background-color: #fdfdff;\n        border-radius: 0.5em;\n        box-shadow: 2px 3px 7px 2px rgba(0,0,0,0.02);\n    }\n    a:link, a:visited {\n        color: #38488f;\n        text-decoration: none;\n    }\n    @media (max-width: 700px) {\n        div {\n            margin: 0 auto;\n            width: auto;\n        }\n    }\n    </style>    \n</head>\n\n<body>\n<div>\n    <h1>Example Domain</h1>\n    <p>This domain is for use in illustrative examples in documents. You may use this\n    domain in literature without prior coordination or asking for permission.</p>\n    <p><a href="https://www.iana.org/domains/example">More information...</a></p>\n</div>\n</body>\n</html>\n'
```

**Comment by simonw** [comment]
Got here:
```diff
diff --git a/llm/default_plugins/openai_models.py b/llm/default_plugins/openai_models.py
index d067109..b1c66e2 100644
--- a/llm/default_plugins/openai_models.py
+++ b/llm/default_plugins/openai_models.py
@@ -1,10 +1,11 @@
 from llm import EmbeddingModel, Model, hookimpl
 import llm
-from llm.utils import dicts_to_table_string, remove_dict_none_values
+from llm.utils import dicts_to_table_string, remove_dict_none_values, logging_client
 import click
 import datetime
 import httpx
 import openai
+import os
 
 try:
     # Pydantic 2
@@ -342,6 +343,8 @@ class Chat(Model):
             kwargs["api_key"] = "DUMMY_KEY"
         if self.headers:
             kwargs["headers"] = self.headers
+        if os.environ.get("LLM_OPENAI_SHOW_RESPONSES"):
+            kwargs["http_client"] = logging_client()
         return openai.OpenAI(**kwargs)
 
     def build_kwargs(self, prompt):
diff --git a/llm/utils.py b/llm/utils.py
index 480aa0f..674693b 100644
--- a/llm/utils.py
+++ b/llm/utils.py
@@ -1,3 +1,5 @@
+import click
+import httpx
 from typing import List, Dict
 
 
@@ -43,3 +45,27 @@ def remove_dict_none_values(d):
             else:
                 new_dict[key] = value
     return new_dict
+
+
+def _log_response(response: httpx.Response):
+    request = response.request
+    click.echo(f"Request: {request.method} {request.url}", err=True)
+    click.echo(f"  Headers:", err=True)
+    for key, value in request.headers.items():
+        if key.lower() == "authorization":
+            value = "[...]"
+        if key.lower() == "cookie":
+            value = value.split("=")[0] + "=..."
+        click.echo(f"    {key}: {value}", err=True)
+    click.echo(f"  Body: {request.content}", err=True)
+    click.echo(f"Response: status_code={response.status_code}", err=True)
+    click.echo(f"  Headers:", err=True)
+    for key, value in response.headers.items():
+        if key.lower() == "set-cookie":
+            value = value.split("=")[0] + "=..."
+        click.echo(f"    {key}: {value}", err=True)
+    click.echo(f"  Body: {response.content}", err=True)
+
+
+def logging_client() -> httpx.Client:
+    return httpx.Client(event_hooks={"response": [_log_response]})
```
The output is weird though:
```bash
LLM_OPENAI_SHOW_RESPONSES=1 llm 'say hi shortly' --no-stream
```
```
Request: POST https://api.openai.com/v1/chat/completions
  Headers:
    host: api.openai.com
    accept-encoding: gzip, deflate
    connection: keep-alive
    accept: application/json
    content-type: application/json
    user-agent: OpenAI/Python 1.10.0
    x-stainless-lang: python
    x-stainless-package-version: 1.10.0
    x-stainless-os: MacOS
    x-stainless-arch: arm64
    x-stainless-runtime: CPython
    x-stainless-runtime-version: 3.10.4
    authorization: [...]
    x-stainless-async: false
    content-length: 109
  Body: b'{"messages": [{"role": "user", "content": "say hi shortly"}], "model": "gpt-4-1106-preview", "stream": false}'
Response: status_code=200
  Headers:
    date: Fri, 26 Jan 2024 16:53:28 GMT
    content-type: application/json
    transfer-encoding: chunked
    connection: keep-alive
    access-control-allow-origin: *
    cache-control: no-cache, must-revalidate
    openai-model: gpt-4-1106-preview
    openai-organization: user-r3e61fpak04cbaokp5buoae4
    openai-processing-ms: 598
    openai-version: 2020-10-01
    strict-transport-security: max-age=15724800; includeSubDomains
    x-ratelimit-limit-requests: 5000
    x-ratelimit-limit-tokens: 5000000
    x-ratelimit-remaining-requests: 4999
    x-ratelimit-remaining-tokens: 4999978
    x-ratelimit-reset-requests: 12ms
    x-ratelimit-reset-tokens: 362ms
    x-request-id: d3ff88d36ce34dd6d9ebc6baaf60b7f2
    cf-cache-status: DYNAMIC
    set-cookie: __cf_bm=...
    server: cloudflare
    cf-ray: 84ba45b01e88172a-SJC
    content-encoding: gzip
    alt-svc: h3=":443"; ma=86400
Request: POST https://api.openai.com/v1/chat/completions
  Headers:
    host: api.openai.com
    accept-encoding: gzip, deflate
    connection: keep-alive
    accept: application/json
    content-type: application/json
    user-agent: OpenAI/Python 1.10.0
    x-stainless-lang: python
    x-stainless-package-version: 1.10.0
    x-stainless-os: MacOS
    x-stainless-arch: arm64
    x-stainless-runtime: CPython
    x-stainless-runtime-version: 3.10.4
    authorization: [...]
    x-stainless-async: false
    cookie: __cf_bm=...
    content-length: 109
  Body: b'{"messages": [{"role": "user", "content": "say hi shortly"}], "model": "gpt-4-1106-preview", "stream": false}'
Response: status_code=200
  Headers:
    date: Fri, 26 Jan 2024 16:53:30 GMT
    content-type: application/json
    transfer-encoding: chunked
    connection: keep-alive
    access-control-allow-origin: *
    cache-control: no-cache, must-revalidate
    openai-model: gpt-4-1106-preview
    openai-organization: user-r3e61fpak04cbaokp5buoae4
    openai-processing-ms: 505
    openai-version: 2020-10-01
    strict-transport-security: max-age=15724800; includeSubDomains
    x-ratelimit-limit-requests: 5000
    x-ratelimit-limit-tokens: 5000000
    x-ratelimit-remaining-requests: 4999
    x-ratelimit-remaining-tokens: 4999978
    x-ratelimit-reset-requests: 12ms
    x-ratelimit-reset-tokens: 362ms
    x-request-id: 465ddb0e69744028e227500e5aaaa49e
    cf-cache-status: DYNAMIC
    server: cloudflare
    cf-ray: 84ba45bc9d6d234f-SJC
    content-encoding: gzip
    alt-svc: h3=":443"; ma=86400
Request: POST https://api.openai.com/v1/chat/completions
  Headers:
    host: api.openai.com
    accept-encoding: gzip, deflate
    connection: keep-alive
    accept: application/json
    content-type: application/json
    user-agent: OpenAI/Python 1.10.0
    x-stainless-lang: python
    x-stainless-package-version: 1.10.0
    x-stainless-os: MacOS
    x-stainless-arch: arm64
    x-stainless-runtime: CPython
    x-stainless-runtime-version: 3.10.4
    authorization: [...]
    x-stainless-async: false
    cookie: __cf_bm=...
    content-length: 109
  Body: b'{"messages": [{"role": "user", "content": "say hi shortly"}], "model": "gpt-4-1106-preview", "stream": false}'
Response: status_code=200
  Headers:
    date: Fri, 26 Jan 2024 16:53:32 GMT
    content-type: application/json
    transfer-encoding: chunked
    connection: keep-alive
    access-control-allow-origin: *
    cache-control: no-cache, must-revalidate
    openai-model: gpt-4-1106-preview
    openai-organization: user-r3e61fpak04cbaokp5buoae4
    openai-processing-ms: 386
    openai-version: 2020-10-01
    strict-transport-security: max-age=15724800; includeSubDomains
    x-ratelimit-limit-requests: 5000
    x-ratelimit-limit-tokens: 5000000
    x-ratelimit-remaining-requests: 4999
    x-ratelimit-remaining-tokens: 4999979
    x-ratelimit-reset-requests: 12ms
    x-ratelimit-reset-tokens: 362ms
    x-request-id: 4e5912ac36666a3b851ec3a327dfcac0
    cf-cache-status: DYNAMIC
    server: cloudflare
    cf-ray: 84ba45cbce52238b-SJC
    content-encoding: gzip
    alt-svc: h3=":443"; ma=86400
Error: Connection error.
```
Why did it make three requests, and why did it end with a connection error?

Maybe the OpenAI library does 3 retries before giving up?

**Comment by simonw** [comment]
Theory: my event hooks are consuming the body of something such that the calling code can't see it any more.

**Comment by simonw** [comment]
Relevant OpenAI code: https://github.com/openai/openai-python/blob/0c1e58d511bd60c4dd47ea8a8c0820dc2d013d1d/src/openai/_streaming.py#L46

```python
def _iter_events(self) -> Iterator[ServerSentEvent]:
        yield from self._decoder.iter(self.response.iter_lines())
```
So maybe I should replace `iter_lines()` with something that prints each line?

**Comment by simonw** [comment]
The fundamental problem here is that with a streaming response it doesn't actually make sense to display the response BEFORE showing the stream of tokens on stdout - because you can't do that, you have to start showing tokens before the stream has finished.

**Comment by simonw** [comment]
Easier option: don't show the response body for streaming responses. People can use `--no-stream` if they want to see the full details.

**Comment by simonw** [comment]
That didn't work - even with `--no-stream` clearly it attempts to call `iter_lines()` under the hood, which then breaks.

**Comment by simonw** [comment]
I'm now seeing this error:

https://github.com/encode/httpx/blob/371b6e946c9e70df3dce79590c195448eac3f635/httpx/_models.py#L899

```python
    def close(self) -> None:
        """
        Close the response and release the connection.
        Automatically called if the response body is read to completion.
        """
        if not isinstance(self.stream, SyncByteStream):
            raise RuntimeError("Attempted to call an sync close on an async stream.")
```
My diff is:
```diff
diff --git a/llm/default_plugins/openai_models.py b/llm/default_plugins/openai_models.py
index d067109..b1c66e2 100644
--- a/llm/default_plugins/openai_models.py
+++ b/llm/default_plugins/openai_models.py
@@ -1,10 +1,11 @@
 from llm import EmbeddingModel, Model, hookimpl
 import llm
-from llm.utils import dicts_to_table_string, remove_dict_none_values
+from llm.utils import dicts_to_table_string, remove_dict_none_values, logging_client
 import click
 import datetime
 import httpx
 import openai
+import os
 
 try:
     # Pydantic 2
@@ -342,6 +343,8 @@ class Chat(Model):
             kwargs["api_key"] = "DUMMY_KEY"
         if self.headers:
             kwargs["headers"] = self.headers
+        if os.environ.get("LLM_OPENAI_SHOW_RESPONSES"):
+            kwargs["http_client"] = logging_client()
         return openai.OpenAI(**kwargs)
 
     def build_kwargs(self, prompt):
diff --git a/llm/utils.py b/llm/utils.py
index 480aa0f..c0576df 100644
--- a/llm/utils.py
+++ b/llm/utils.py
@@ -1,4 +1,6 @@
-from typing import List, Dict
+import click
+import httpx
+from typing import List, Dict, Iterator
 
 
 def dicts_to_table_string(
@@ -43,3 +45,45 @@ def remove_dict_none_values(d):
             else:
                 new_dict[key] = value
     return new_dict
+
+
+class LoggingStream:
+    def __init__(self, stream):
+        self._stream = stream
+
+    def __iter__(self) -> Iterator[bytes]:
+        for chunk in self._stream:
+            click.echo(chunk, err=True)
+            yield chunk
+
+    def close(self):
+        # isinstance() check avoids a RuntimeError
+        if isinstance(self._stream, httpx.SyncByteStream):
+            self._stream.close()
+
+
+def _log_response(response: httpx.Response):
+    request = response.request
+    click.echo(f"Request: {request.method} {request.url}", err=True)
+    click.echo(f"  Headers:", err=True)
+    for key, value in request.headers.items():
+        if key.lower() == "authorization":
+            value = "[...]"
+        if key.lower() == "cookie":
+            value = value.split("=")[0] + "=..."
+        click.echo(f"    {key}: {value}", err=True)
+    click.echo(f"  Body: {request.content}", err=True)
+    click.echo(f"Response: status_code={response.status_code}", err=True)
+    click.echo(f"  Headers:", err=True)
+    for key, value in response.headers.items():
+        if key.lower() == "set-cookie":
+            value = value.split("=")[0] + "=..."
+        click.echo(f"    {key}: {value}", err=True)
+    # # If it's not streaming, show the body here too
+    # if "stream" not in response.headers.get("content-type", ""):
+    #     click.echo(f"  Body: {response.content}", err=True)
+    response.stream = LoggingStream(response.stream)
+
+
+def logging_client() -> httpx.Client:
+    return httpx.Client(event_hooks={"response": [_log_response]})

```

**Comment by simonw** [comment]
This almost works:
```python
from httpx._transports.default import ResponseStream


class _LoggingStream(ResponseStream):
    def __iter__(self) -> Iterator[bytes]:
        for chunk in super().__iter__():
            click.echo(f"  Chunk: {chunk}", err=True)
            yield chunk


def _log_response(response: httpx.Response):
    request = response.request
    click.echo(f"Request: {request.method} {request.url}", err=True)
    click.echo(f"  Headers:", err=True)
    for key, value in request.headers.items():
        if key.lower() == "authorization":
            value = "[...]"
        if key.lower() == "cookie":
            value = value.split("=")[0] + "=..."
        click.echo(f"    {key}: {value}", err=True)
    click.echo(f"  Body: {request.content}", err=True)
    click.echo(f"Response: status_code={response.status_code}", err=True)
    click.echo(f"  Headers:", err=True)
    for key, value in response.headers.items():
        if key.lower() == "set-cookie":
            value = value.split("=")[0] + "=..."
        click.echo(f"    {key}: {value}", err=True)
    response.stream._stream = _LoggingStream(response.stream._stream)
```
Output:
```
Request: POST https://api.openai.com/v1/chat/completions
  Headers:
    host: api.openai.com
    accept-encoding: gzip, deflate
    connection: keep-alive
    accept: application/json
    content-type: application/json
    user-agent: OpenAI/Python 1.10.0
    x-stainless-lang: python
    x-stainless-package-version: 1.10.0
    x-stainless-os: MacOS
    x-stainless-arch: arm64
    x-stainless-runtime: CPython
    x-stainless-runtime-version: 3.10.4
    authorization: [...]
    x-stainless-async: false
    content-length: 108
  Body: b'{"messages": [{"role": "user", "content": "say hi shortly"}], "model": "gpt-4-1106-preview", "stream": true}'
Response: status_code=200
  Headers:
    date: Fri, 26 Jan 2024 18:20:40 GMT
    content-type: text/event-stream
    transfer-encoding: chunked
    connection: keep-alive
    access-control-allow-origin: *
    cache-control: no-cache, must-revalidate
    openai-model: gpt-4-1106-preview
    openai-organization: user-r3e61fpak04cbaokp5buoae4
    openai-processing-ms: 232
    openai-version: 2020-10-01
    strict-transport-security: max-age=15724800; includeSubDomains
    x-ratelimit-limit-requests: 5000
    x-ratelimit-limit-tokens: 5000000
    x-ratelimit-remaining-requests: 4999
    x-ratelimit-remaining-tokens: 4999979
    x-ratelimit-reset-requests: 12ms
    x-ratelimit-reset-tokens: 362ms
    x-request-id: 94f746a3370228e5c0ba7a134872fa77
    cf-cache-status: DYNAMIC
    set-cookie: __cf_bm=...
    server: cloudflare
    cf-ray: 84bac56b9b992542-SJC
    alt-svc: h3=":443"; ma=86400
  Chunk: b'data: {"id":"chatcmpl-8lL6daxibkqvrYiBsDrlQJXWkGugo","object":"chat.completion.chunk","created":1706293239,"model":"gpt-4-1106-preview","system_fingerpr'
  Chunk: b'int":"fp_de93422283","choices":[{"index":0,"delta":{"role":"assistant","content":""},"logprobs":null,"finish_reason":null}]}\n\n'
  Chunk: b'data: {"id":"chatcmpl-8lL6daxibkqvrYiBsDrlQJXWkGugo","object":"chat.completion.chunk","created":1706293239,"model":"gpt-4-1106-preview","system_fingerprint":"fp_de93422283","choices":[{"index":0,"delta":{"content":"Hi"},"logprobs":null,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-8lL6daxibkqvrYiBsDrlQJXWkGugo","object":"chat.completion.chunk","created":1706293239,"model":"gpt-4-1106-preview","system_fingerprint":"fp_de93422283","choices":[{"index":0,"delta":{"content":"!"},"logprobs":null,"finish_reason":null}]}\n\ndata: {"id":"chatcmpl-8lL6daxibkqvrYiBsDrlQJXWkGugo","object":"chat.completion.chunk","created":1706293239,"model":"gpt-4-1106-preview","system_fingerprint":"fp_de93422283","choices":[{"index":0,"delta":{},"logprobs":null,"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n'
```
But with `--no-stream` I get:
```
  Chunk: b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03T\x90MS\xc20\x10\x86\xef\xfd\x15q\xcf\xd4iSD\xe8\xd1\xd1\x19\xbf\x0f^\x1d\xa7S\xd2\xa5\x04\xd3lL\x16\x15\x19\xfe\xbb\x93R@/9\xbco\x9e\xcd\xb3\xd9&B\x80n\xa0\x14\xa0\x965\xab\xce\x99tj\x1e/\x8b\x8d\xb5v\xfat\xf7|\xff1^\xa3\xca\xe4\xd5\xe6z\xf5\xf0\xf3r\x03\xa3H\xd0|\x85\x8a\x0f\xd4\xb9\xa2\xce\x19dMv_+\x8f5c\x9c\x9a_f\x139+\xe4\xe4\xa2/:'
  Chunk: b'j\xd0D\xacu\x9c\x8e\xd3<\xcf&\xa9\xf3\xf8\xa9\xf1k \x97\xa4\x15\x06(\xc5k"\x84\x10\xdb\xfe\x8c\x8e\xb6\xc1o(E6:$\x1d\x86P\xb7\x08\xe5\xf1\x92\x10\xe0\xc9\xc4\x04\xea\x10t\xe0\xda2\x8cN\xa5"\xcbh{\xed[}\x06C\xb1;N4\xd4:O\xf3\xf8\xba]\x1bs\xcc\x17\xda\xea\xb0\xac<\xd6\x81l\xa4\x03\x93\xdb\xe3\xbbD\x88\xb7\xde|\xfdO\x06\x9c\xa7\xceq\xc5\xf4\x8e6\x0e\xcc\x07q8\xfd\xd5\xa9\x94C\xc7\xc4\xb5\xf9\xc3\xc8d\xd0\x83\xb0\t\x8c]\xb5\xd0\xb6E\xef\xbc\xdeo\xb1pU\x83\xb3b,\xa5\x9c\x16\x90\xec\x92_\x00\x00\x00\xff\xff\x03\x00sG:\x03\xcf\x01\x00\x00'
```
Which looks like data that has not been un-gzipped.
