### ISSUE TITLE
Can't add HTTP authentication headers from CLI

### ISSUE THREAD

**Issue by akaihola** [simonw/llm#551]
I'm using a private provider which needs an authentication token as an HTTP header.

I've created this `extra-openai-models.yaml` (in the directory shown by `llm logs path`):
```yaml
- api_base: https://api.myprovider.com/path
  api_key_name: openai
  model_id: myprovider
  model_name: gpt-4o
```

I can then do this in Python code:
```python
model = llm.get_model(myprovider)
model.headers = {"Auth-Token": "<my authentication token>"}
response = model.prompt("Do you read me?")
```

But I can't find a way to pass the headers when using `llm` on the command line – neither as arguments nor in a configuration file.

Apart from creating a wrapper script with monkeypatching or running my own fork of `llm`, other ideas?

**Comment by akaihola** [comment]
I successfully created a monkeypatching wrapper script:

```python
from unittest.mock import patch
import llm.cli

def get_model_aliases():
    result = llm.get_model_aliases()
    model = result["myprovider"]
    try:
        model.key = model.get_key()
    except llm.NeedsKeyException as exc_info:
        model.key = input(f"{exc_info}\nor enter the authentication token below.\nToken: ")
    model.headers = {"Auth-Token": model.key}
    return result

with patch("llm.cli.get_model_aliases", get_model_aliases):
    llm.cli.cli()
```

**Comment by simonw** [comment]
Did you try the `headers:` thing in the YAML file? https://llm.datasette.io/en/stable/other-models.html#extra-http-headers

```yaml
- api_base: https://api.myprovider.com/path
  api_key_name: openai
  model_id: myprovider
  model_name: gpt-4o
  headers:
    Auth-Token: auth-token
```
