### ISSUE TITLE
Include file contents in `llm chat`

### ISSUE THREAD

**Issue by jritsema** [simonw/llm#682]
Curious, is there a way to inject the contents of a file while in the middle of a chat?  If not, I'd love to be able to do something like `!file foo.txt`

**Comment by spm1001** [comment]
Similarly I'd love to be able to start a chat with a corpus of input (text files, images), plus an initial prompt, then continue the conversation, but `cat Screenshot\ 2024-12-12\ at\ 14.06.20.png | llm chat "describe this image and then let's talk about it" -a - -m gemini-2.0-flash-exp` gives.  (I'm assuming/hoping this will mean that I don't have to re-transmit the image for each 'turn' in the chat.)

```
Usage: llm chat [OPTIONS]
Try 'llm chat --help' for help.

Error: No such option: -a
```

**Comment by Grynn** [comment]
Something like @<filename> instead of !file <filename> would be cleaner I think
Copilot in VSCode & Cursor do this, meaning they let you type @<filename> to attach a file. 

GitHub's issue editor uses `#` to reference issues and `@` to reference people. 

One way to do this might be an additional hook: prepare-prompt, which allows plugins to modify a prompt before it is executed by the model. The context could/should include file attachments, model id etc. Something like:

```yaml
context:
  attachments:
    - { filename, mimeType, handle }
  model-id:
  model-name:
  prompt:
  conversation id: #if continuing an existing conversation.
```

You'd need handle & mimetype for when the input is not a file on disk, but a pipe.

Then people can make and activate their own plugins like:
* llm-ctx-attach-files
