### ISSUE TITLE
Include usage information in llm logs --prompts -u

### ISSUE THREAD

**Issue by simonw** [simonw/llm#756]
Currently:
```bash
llm logs -cu --prompts
```
Outputs this, ignoring the `-u/--usage` flag:
```yaml
- model: o3-mini
  datetime: 2025-02-16T17:24:53
  conversation: 01jm7ws28pqj8zfs4f2f2khgv5
  prompt: <documents> <document index="1"> <source>./setup.py</source> <document_content> 1 from setuptools import setup, find_...
  usage: 141,315 input, 6,667 output, {"completion_tokens_details": {"reasoning_tokens": 5696}, "prompt_tokens_details": {"cached_tokens": 3584}}
```

**Comment by simonw** [comment]
First prototype did this:
```yaml
- model: o3-mini
  datetime: 2025-02-16T17:24:53
  conversation: 01jm7ws28pqj8zfs4f2f2khgv5
  prompt: <documents> <document index="1"> <source>./setup.py</source> <document_content> 1 from setuptools import setup, find_...
  usage: 141,315 input, 6,667 output, {"completion_tokens_details": {"reasoning_tokens": 5696}, "prompt_tokens_details": {"cached_tokens": 3584}}
```
I think something like this would be neater:
```yaml
- model: o3-mini
  datetime: 2025-02-16T17:24:53
  conversation: 01jm7ws28pqj8zfs4f2f2khgv5
  prompt: <documents> <document index="1"> <source>./setup.py</source> <document_content> 1 from setuptools import setup, find_...
  usage:
    input: 141315
    output: 6667
    details: {"completion_tokens_details": {"reasoning_tokens": 5696}, "prompt_tokens_details": {"cached_tokens": 3584}}
```
I should probably switch to using a YAML library rather than hand-assembling the YAML.

**Comment by simonw** [comment]
First prototype:
```diff
@@ -1071,6 +1074,14 @@ def logs_list(
                     for attachment in attachments:
                         path = attachment["path"] or attachment["url"]
                         lines.append("  - {}: {}".format(attachment["type"], path))
+                if usage:
+                    token_usage = token_usage_string(
+                        row["input_tokens"],
+                        row["output_tokens"],
+                        json.loads(row["token_details"]) if row["token_details"] else None,
+                    )
+                    if token_usage:
+                        lines.append("  usage: {}".format(token_usage))
```

**Comment by simonw** [comment]
I can use a pattern like this:
```pycon
>>> for item in [{"age": 30, "name": "Alice"}, {"age": 35, "name": "Terry"}]:
...     print(yaml.dump([item]).strip())
... 
- age: 30
  name: Alice
- age: 35
  name: Terry
```

**Comment by simonw** [comment]
I might rename `--prompts` to `-s/--short` instead as that's less to type and gets a good short option.

**Comment by simonw** [comment]
Prototype:
```bash
llm logs --prompts --cid 01jm66v4q94hjwnrgktvhe6b5n -u
```
```yaml
- model: chatgpt-4o-latest
  datetime: '2025-02-16T01:44:18'
  conversation: 01jm66v4q94hjwnrgktvhe6b5n
  prompt: describe image
  attachments:
  - type: image/jpeg
    url: https://static.simonwillison.net/static/2024/pelicans.jpg
  usage:
    input: 264
    output: 116
```
