### ISSUE TITLE
--short should show the end of the prompt too

### ISSUE THREAD

**Issue by simonw** [simonw/llm#759]
Eg for:

```yaml
- model: gemini-2.0-pro-exp-02-05
  datetime: '2025-02-14T23:23:57'
  conversation: 01jm3cek8eb4z8tkqhf4trk98b
  prompt: '<documents> <document index="1"> <source>./LORA.md</source> <document_content>
    # Fine-Tuning with LoRA or QLoRA You c...'
  usage:
    input: 162885
    output: 2558
```
I often dump a ton of context into the prompt and then put an instruction like "explain how this works" at the end.

**Comment by sukhbinder** [comment]
This PR https://github.com/simonw/llm/pull/820 addresses this issue.

llm logs --short

```yaml
- model: llama3.2:latest
  datetime: '2025-03-08T05:30:12'
  conversation: 01jnt3sgj23z38sz6j673p59a3
  prompt: import asyncio import click from click_default_group impo...  Explain
    this code in detail and with practical examples
```
