### ISSUE TITLE
[Question] Is it possible to use cutom embedding model?

### ISSUE THREAD

**Issue by dhruvinsh** [simonw/llm#762]
I have configured `extra-openai-models.yaml` as,
```yaml
- model_id: azure-text-embedding-3-large
  model_name: azure-text-embedding-3-large
  api_base: "http://10.16.136.20:4100"
```

but when I try to set it as default embed model I get error as,
```
llm embed-models default azure-text-embedding-3-large
Error: Unknown embedding model: azure-text-embedding-3-large
```
