### ISSUE TITLE
Attachments support for templates

### ISSUE THREAD

**Issue by simonw** [simonw/llm#826]
It should be possible to save attachments as part of a template.

Three parts to this:

- [x] Support `attachments:` in the template YAML
- [x] Ensure `llm -a ... --save templatename` works
- [x] When a template has attachments they should be used when running `llm -t templatename`

**Comment by simonw** [comment]
Three parts to this:

- [ ] Support `attachments:` in the template YAML
- [ ] Ensure `llm -a ... --save templatename` works
- [ ] When a template has attachments they should be used when running `llm -t templatename`

**Comment by simonw** [comment]
I also need to support the equivalent of the `--attachment-typj image.jpg image/jpeg` option in that YAML format.

Easiest design:
```yaml
attachments:
- https://static.simonwillison.net/static/2025/two-pelicans.jpg
attachment_types:
- type: image/jpeg
  value: https://static.simonwillison.net/static/2025/two-pelicans.jpg
```
