### ISSUE TITLE
allow custom OpenAI endpoint (or document it)

### ISSUE THREAD

**Issue by khimaros** [simonw/llm#892]
it would be great to be able to use OpenAI compatible APis with `llm`, such the built in llama.cpp server (llama-server). if this is already supported, it would be helpful to document configuration required.

**Comment by khimaros** [comment]
FWIW, i tested the usual way of setting `OPENAI_API_BASE` env var

**Comment by khimaros** [comment]
i see, this is solved with adding a file `${XDG_CONFIG_HOME}/io.datasette.llm/extra-openai-models.yaml` and content like:

```yaml
- model_id: llama-cpp
  model_name: llama-cpp
  api_base: "http://localhost:7860"
```
