### ISSUE TITLE
llm models --options should show the key and environment variable for models with keys

### ISSUE THREAD

**Issue by simonw** [simonw/llm#903]
Idea and implementation by @smorin - opening this issue to track things for release notes.

**Comment by simonw** [comment]
This is now ready to land in:
- #877

**Comment by simonw** [comment]
```bash
llm models --options
```
Output now includes things like this:
```
OpenAI Chat: gpt-4o-mini (aliases: 4o-mini, mini)
  Options:
    temperature: float
    max_tokens: int
    top_p: float
    frequency_penalty: float
    presence_penalty: float
    stop: str
    logit_bias: dict, str
    seed: int
    json_object: boolean
  Attachment types:
    application/pdf, image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
  Keys:
    key: openai
    env_var: OPENAI_API_KEY
GeminiPro: gemini-1.5-flash-latest (aliases: flash)
  Options:
    code_execution: boolean
    temperature: float
    max_output_tokens: int
    top_p: float
    top_k: int
    json_object: boolean
    google_search: boolean
  Attachment types:
    application/ogg, application/pdf, audio/aac, audio/aiff,
    audio/flac, audio/mp3, audio/mpeg, audio/ogg, audio/wav,
    image/heic, image/heif, image/jpeg, image/png, image/webp,
    text/csv, text/plain, video/3gpp, video/avi, video/mov, video/mp4,
    video/mpeg, video/mpg, video/quicktime, video/webm, video/wmv,
    video/x-flv
  Features:
  - streaming
  - schemas
  - async
  Keys:
    key: gemini
    env_var: LLM_GEMINI_KEY
Anthropic Messages: anthropic/claude-3-haiku-20240307 (aliases: claude-3-haiku)
  Options:
    max_tokens: int
    temperature: float
    top_p: float
    top_k: int
    user_id: str
    prefill: str
    hide_prefill: boolean
    stop_sequences: array, str
  Attachment types:
    image/gif, image/jpeg, image/png, image/webp
  Features:
  - streaming
  - schemas
  - async
  Keys:
    key: anthropic
    env_var: ANTHROPIC_API_KEY
```
