### ISSUE TITLE
Allow -s/--system to add or override system prompt from a template

### ISSUE THREAD

**Issue by simonw** [simonw/llm#916]
Currently if you run `-t` and `--system` together you get:

> `Cannot use -t/--template and --system together`

But not all templates even set a system prompt. In this case I wanted to use it with this template:
```yaml
model: anthropic/claude-3-7-sonnet-latest
name: think
options:
    thinking: true
    thinking_budget: 16000
```
