### ISSUE TITLE
Allow providing options in alias or model definition

### ISSUE THREAD

**Issue by mqudsi** [simonw/llm#930]
It would be very convenient to allow defining an alias such as `o3-mini-high` that is an alias for `o3-mini` but also automatically supplies `-o reasoning high`. In particular, it makes it easier to use shell completions and to swap out one model for the other when testing a different response to the previously executed `llm` shell command from bash/shell history (only edit the `-m` payload and not have to also add or remove 3 additional arguments, especially if you're comparing, say, o3-mini-medium vs gemini-2.5 vs o3-mini-high or whatever where it's not the same base model).

Alternatively, if it could be defined in a models `.yaml` instead of in the `alias.yaml` as a separate model, for example

```yaml
﻿- model_id: o3-mini-high
  model_name: o3-mini
  model_args:
  - reasoning: high

- model_id: o3-mini-medium
  model_name: o3-mini
  model_args:
  - reasoning: medium
```
